### PR TITLE
Fix skipping first row

### PR DESCRIPTION
**Pull request by bomshteyn**
since `$row_number = $row_index + 1;` `$row_number < $start_row_number` will return false on first row. The current code was still validating first row unless `$start_row_number` was set to 2

### CODE REVIEW

**Comment by SUKOHI** [comment]
Hi, bomshteyn.
Thank you for your pullrequest.

However, I guess what you mentioned is a specification as I wrote in README.md.(Actually Hugo Leon wrote the comment for me) like this.

> 'start_row' => 1,   // <- Starting validation from row one, not zero

Because Excel sheet's row starts from 1.

**Comment by bomshteyn** [comment]
@SUKOHI i understand, but `$row_number = $row_index + 1;` so the least it's ever going to be is 1 never 0 as a result `$row_number < $start_row_number` will never be true. So either it needs to be changed to `$row_index < $start_row_number` or the readme should be updated to the following:

> 'start_row' => 2, // <- Starting validation from row two, not one

**Comment by SUKOHI** [comment]
bomshteyn, thank you for your reply.

Umm, I'm misunderstanding??
I actually have checked it as follows.

Now, I have a CSV file including like this.

1 | (blank)
2 | row 2
3 | row 3
4 | row 4
5 | row 5

Then, I submitted this csv file to a route that CsvValidator is waiting for.

$csv_rules = [
    0 => 'required' // means A column
];
$options = [
    'start_row' => 1, // means from A1
    'end_row' => 4,
];
$request->validate([
    'csv' => new Csv($csv_rules, $options)
]);

In this case, I got an error because A1 is blank.
And when I changed `start_row` to 2, passed successfully.

Is this wrong?

**Comment by bomshteyn** [comment]
> And when I changed `start_row` to 2, passed successfully.

That is exactly my point according to the readme file you either set `start_row` to `0` or to `1` 

> Starting validation from row one, not zero

That is the confusing part.

**Comment by SUKOHI** [comment]
After considering your opinion, I added an explanation to `README.md`.
Thank you for the contribution.😊

**Pull request closed without merging**
